[package]
name = "asstosrt_wasm"
version = "0.1.0"
authors = ["sorz <orz@sorz.org>"]

[dependencies]
stdweb = "0.4.8"
regex = "1.0"
lazy_static = "1.1"
encoding = "0.2"
chardet = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
simplecc = "0.1"
crc = "1.8.1"
